Stat svc
TatianaAV/java-explore-with-me pull request #3
Opened 2023-03-17 20:34 UTC by TatianaAV

2023-03-18 11:40 UTC, NikolaiDem requested changes

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +@SpringBootApplication
StatsClient - это @Service, который содержит методы для формирования и отправки http запросов на эндпоинты EndpointController-а. Необходимо добавить реализацию таких методов.

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/java/ru/practicum/controller/EndpointController.java
> +    @GetMapping("/test")
HealthCheck?

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/java/ru/practicum/handler/ErrorHandler.java
> +    public ErrorResponse handle(final Throwable e) {
Spring не обрабатывает Throwable, лучше понизить до Exception. А еще лучше выделить в отдельный метод ошибки валидации.

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/java/ru/practicum/service/EndpointServiceImpl.java
> +                log.info("stats.size {}", stats.size());
Почему логирование только для ветки else ? Лучше вынести за пределы условий.

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/resources/schema.sql
> +create table if not exists endpoints(
Еще лучше сделать таблицу с приложениями, где будет его id и название.
Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу endpoints.

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/resources/schema.sql
> +                          ip varchar(255) not null ,
Для ip 255 char-ов выглядит слишком много.

2023-03-18 11:40 UTC, NikolaiDem commented on stats/stats-server/src/main/resources/schema.sql
> +                          id BIGINT generated by default as identity not null ,
На id добавить ограничение первичного ключа.

2023-03-21 15:37 UTC, TatianaAV commented on docker-compose.yml
> +      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
А если мне эта конфигурация нужна для тестирования, то как сделать? отдельным файлом и запуск его, если не используется докер?

2023-03-21 16:21 UTC, TatianaAV commented on stats/stats-client/src/main/java/ru/practicum/StatsClient.java
> +@SpringBootApplication
на вебинаре сказали, что в первой части не обязательно.  сделала.

2023-03-21 16:23 UTC, TatianaAV commented on stats/stats-server/src/main/java/ru/practicum/controller/EndpointController.java
> +    @GetMapping("/test")
начала делать без тестов из git. написала свои тесты, а потом забыла убрать, так как свои добавила в тест от курса.

2023-03-22 20:15 UTC, NikolaiDem commented on docker-compose.yml
> +      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
Да, последнее предложение было лишним)

2023-03-23 11:29 UTC, merged