Main svc
TatianaAV/java-explore-with-me pull request #4
Opened 2023-05-08 16:15 UTC by TatianaAV

2023-05-11 11:45 UTC, TatianaAV commented
С нетерпением жду комментариев. ТЗ немного запутано, много непонятного.

2023-05-11 23:38 UTC, NikolaiDem requested changes

2023-05-11 23:38 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/model/Compilation.java
> +    @ManyToOne(cascade = CascadeType.ALL)
Лучше сделать Lazy инициализацию, чтобы уменьшить нагрузку на БД (N+1 issue)
https://vladmihalcea.com/n-plus-1-query-problem/
Аналогично для всех entities

2023-05-11 23:38 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/repository/EventCustomRepository.java
> +        if (rangeStart != null && rangeEnd != null) {
А отдельно по rangeStart или rangeEnd поиск не предполагался ?)

2023-05-11 23:38 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/service/compilation/CompilationServiceImpl.java
> +        for (CompilationDto compilationDto1 : compilations) {
Вложенных циклов лучше избегать, можно переделать один список в мапу и использовать один цикл

2023-05-13 17:17 UTC, TatianaAV commented on main-serv/src/main/java/ru/practicum/mainservice/model/Compilation.java
> +    @ManyToOne(cascade = CascadeType.ALL)
Она же по умолчанию Lazy, лучше явно прописывать?

2023-05-13 17:35 UTC, TatianaAV commented on main-serv/src/main/java/ru/practicum/mainservice/repository/EventCustomRepository.java
> +        if (rangeStart != null && rangeEnd != null) {
подумалось, что искать нужно всегда между датами и они нужны всегда обе. ;)

2023-05-14 14:58 UTC, NikolaiDem approved these changes

2023-05-14 15:43 UTC, merged