Feature comments
TatianaAV/java-explore-with-me pull request #6
Opened 2023-05-20 12:29 UTC by TatianaAV

2023-05-21 14:07 UTC, NikolaiDem requested changes
Из Event тоже лучше удалить views и confirmedRequests

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/controller/comments/PrivateCommentApiController.java
> +public class PrivateCommentApiController {
Для валидации необходимо добавить @Validated

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/controller/comments/PrivateCommentApiController.java
> +        log.info("POST PrivateCommentApiController/ addComment/ userId {}", userId);
Задублировалось

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/controller/comments/PrivateCommentApiController.java
> +public class PrivateCommentApiController {
Контролер называется Private, но обработчики в нем private, public и admin

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/dto/comment/StateComment.java
> +            if (String.valueOf(b.value).equals(text)) {
String.valueOf(...) здесь выглядит лишним

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/dto/comment/NewCommentDto.java
> +
При обновлении указана длина комментария, а при добавлении ?)

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/mapper/CommentMapper.java
> +    @Mapping(target = "id", source = "comment.id")
Явные маппинги здесь лишние )

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/mapper/CommentMapper.java
> +    @Mapping(target = "id", source = "comment.id")
И здесь тоже

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/model/Comment.java
> +    private Long views;
Поле не нужно, сейчас оно используется лишь для временного хранения просмотров перед маппингом в dto, лучше в метод маппинга Comment в CommentDto передавать сам Comment и viewsCount

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/service/comment/CommentService.java
> +    @Transactional(readOnly = true)
Для чего здесь Transactional?
Аналогично для остальных методов

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/java/ru/practicum/mainservice/service/comment/CommentServiceImpl.java
> +        sendStatistics(request);
Какая логика в "просмотры комментариев" предполагалась ? Почему статистика только в этом методе обновляется?)

2023-05-21 14:07 UTC, NikolaiDem commented on main-serv/src/main/resources/schema.sql
> +    views         BIGINT,
Поле избыточно

2023-05-23 18:03 UTC, TatianaAV commented on main-serv/src/main/java/ru/practicum/mainservice/service/comment/CommentServiceImpl.java
> +        sendStatistics(request);
Сколько пользователей посмотрело комментарий, мне кажется, интересно только, тому, кто написал его.

2023-05-23 22:08 UTC, TatianaAV commented
Спасибо за комментарии. Задержалась из-за новых тестов.

2023-05-24 20:17 UTC, NikolaiDem approved these changes

2023-05-25 12:07 UTC, merged